### ISSUE TITLE
How to include/use

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp-stagger#1]
Hi,
I there a description on how this graphaware stagger jar could be used togheter with 
graphaware-nlp, graphaware-server-community-all.jar?

Should the jar be placed in plug-in folder togheter with a specific version of graphaware-nlp and should a spcific command be used?
example
CALL ga.nlp.processor.addPipeline({textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', name: 'customStopWords', processingSteps: {tokenize: true, ner: true, dependency: false}, stopWords: '+,result, all, during', 
threadNumber: 20})

Should com.graphaware.nlp.processor.stanford.StanfordTextProcessor be replaced with com.graphaware.nlp.stagger

Used versions:
graphaware-nlp-3.5.2.53.16.jar
graphaware-server-enterprise-all-3.5.3.53.jar
nlp-stanfordnlp-3.5.2.53.17.jar

Regards
//Andraes

**Comment by ikwattro** [comment]
Replied by email, as this is part of a commercial training.
